server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态动态创建路由的功能,利用微服务名进行路由
      routes:
        - id: payment_routh #payment_routh    # 路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://CLOUD-PROVIDER-SERVICE   # URI的协议为lb 表示启用 Getaway的负载均衡功能 实现动态路由
          # uri: http://localhost:8001         # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**          # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_routh   # 路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://CLOUD-PROVIDER-SERVICE   # URI的协议为lb 表示启用 Getaway的负载均衡功能
          # uri: http://localhost:8001          # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**             # 断言，路径相匹配的进行路由

#            - After=2020-04-15T11:46:19.781+08:00[Asia/Shanghai] # 当前时区之后才能访问
#            - Between=2020-04-15T11:46:19.781+08:00[Asia/Shanghai],2020-04-15T12:46:19.781+08:00[Asia/Shanghai]

#            - Cookie=username,gujunbin
#            cmd 访问 curl http://localhost:9527/payment/lb --cookie "username=gujunbin"

#            - Header=X-Request-Id, \d+
#              请求头需要有X-Request-Id属性名,值为整数正则表达式
#              cmd curl http://localhost:9527/payment/lb -H "X-Request-Id:1234"

            - Method=GET
            - Query=username, \d+  # 要参数名username且值为正数  

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #      defaultZone: http://eureka7002.com:7002/eureka/
      #      单机版eureka
      defaultZone: http://eureka7001.com:7001/eureka/